version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "8545:8545"
    command: -m 'fetch local valve black attend double eye excite planet primary install'
networks:
    default:
        external:
            name: cloudbuild